[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/contracts/=lib/foundry-chainlink-toolkit/src/",
]
[profile.ci]
fuzz = { runs = 10 }
invariant = { runs = 10 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
ethereum = "${ETHEREUM_FORK_NODE_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
